<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Colegio;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    private function base(array $overrides): array
    {
        // Todas las columnas con default null
        return array_merge([
            'area' => null,
            'curso1' => null,
            'curso2' => null,
            'curso3' => null,
            'curso4' => null,
            'curso5' => null,
            'curso6' => null,
            'titulo_fecha1' => null,
            'fecha1' => null,
            'titulo_fecha2' => null,
            'fecha2' => null,
            'lugar' => null,
            'modalidad' => null,
            'inscripcion' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ], $overrides);
    }

    public function run(): void{
        DB::table('areas')->insert([
            $this->base([
                'area' => 'QUÍMICA',
                'curso1' => '1º Secundaria',
                'curso2' => '2º Secundaria',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Competencia Teórica',
                'fecha1' => '2025-09-05',
                'titulo_fecha2' => 'Competencia Experimental',
                'fecha2' => '2025-09-12',
                'lugar' => 'Laboratorios del Depto. de Química – Bloque 300',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Prueba teórica hasta el 02/09/2025 18:00; experimental hasta el 09/09/2025 18:00, en secretaria del Depto. de Química – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'MEDIO AMBIENTE',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Competencia Única',
                'fecha1' => '2025-09-06',
                'titulo_fecha2' => null,
                'fecha2' => null,
                'lugar' => 'Ambientes de la carrera Ing. Química e Ing. de Alimentos',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Del 27/08/2025 al 03/09/2025, en secretaria de Ing. Química e Ing. de Alimentos – Ciudadela Universitaria F.N.I. (9:00–12:00 y 15:00–17:00).',
            ]),
            $this->base([
                'area' => 'BIOLOGÍA',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Competencia Única',
                'fecha1' => '2025-09-10',
                'titulo_fecha2' => null,
                'fecha2' => null,
                'lugar' => 'Ciudadela Universitaria',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 29/08/2025 12:00, en secretaria de Ing. Química e Ing. de Alimentos – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'FÍSICA',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Prueba Experimental',
                'fecha1' => '2025-10-14',
                'titulo_fecha2' => 'Prueba Teórica',
                'fecha2' => '2025-10-14',
                'lugar' => 'Laboratorio de Física – Bloque 300',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 12/09/2025 12:00, en el Laboratorio de Física Virtual (Aula 101, Bloque Hugo Murillo Benich – Ciudadela Universitaria F.N.I.).',
            ]),
            $this->base([
                'area' => 'MATEMÁTICA',
                'curso1' => '1º Secundaria',
                'curso2' => '2º Secundaria',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Etapa Clasificatoria',
                'fecha1' => '2025-09-19',
                'titulo_fecha2' => 'Etapa Final',
                'fecha2' => '2025-10-01',
                'lugar' => 'Bloque 300',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Del 03/09/2025 al 12/09/2025, Oficina de la Olimpiada Matemática Oruro – Bloque 300, 2º piso (9:00–12:00).',
            ]),
            $this->base([
                'area' => 'GEOGRAFÍA',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Competencia Única',
                'fecha1' => '2025-09-26',
                'titulo_fecha2' => null,
                'fecha2' => null,
                'lugar' => 'Bloque 300',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 24/09/2025 17:00, en secretaria de Ingeniería Geológica – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'ASTRONOMÍA Y ASTROFÍSICA',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Prueba Teórica',
                'fecha1' => '2025-10-05',
                'titulo_fecha2' => 'Prueba Observacional',
                'fecha2' => '2025-10-05',
                'lugar' => 'Bloque 300 – Aula 101, Bloque Hugo Murillo Benich',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 03/10/2025 12:00, Laboratorio de Física Virtual – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'ENERGÍAS',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Prueba Teórica',
                'fecha1' => '2025-10-12',
                'titulo_fecha2' => 'Prueba Experimental',
                'fecha2' => '2025-10-12',
                'lugar' => 'Carrera de Ing. Mecánica, Electromecánica, Mecatrónica',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 10/10/2025 16:00, en secretaria de la carrera – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'PROGRAMACIÓN',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Warm Up',
                'fecha1' => '2025-10-21',
                'titulo_fecha2' => 'Competencia',
                'fecha2' => '2025-10-22',
                'lugar' => 'Ingeniería de Sistemas e Informática',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Del 01/09/2025 al 10/10/2025, en secretaria de la Carrera de SIS-INF – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'REDES Y CIBERSEGURIDAD',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Nivel 1',
                'fecha1' => '2025-10-23',
                'titulo_fecha2' => 'Nivel 2',
                'fecha2' => '2025-10-23',
                'lugar' => 'Laboratorios Bloque B y C – SISINF',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Del 01/10/2025 al 20/10/2025, secretaria Academia Cisco SISFNIUTO – Edif. 3 de Julio.',
            ]),
            $this->base([
                'area' => 'ROBÓTICA',
                'curso1' => '1º Secundaria',
                'curso2' => '2º Secundaria',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Registro',
                'fecha1' => '2025-10-24',
                'titulo_fecha2' => 'Prueba',
                'fecha2' => '2025-10-24',
                'lugar' => 'Ciudadela Universitaria – Bloque B SISINF',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Del 01/10/2025 al 22/10/2025, en secretaria de SIS-INF – Ciudadela Universitaria F.N.I.',
            ]),
            $this->base([
                'area' => 'DISEÑADORES Y FABRICADORES',
                'curso1' => '1º Secundaria',
                'curso2' => '2º Secundaria',
                'curso3' => '3º Secundaria',
                'curso4' => '4º Secundaria',
                'curso5' => '5º Secundaria',
                'curso6' => '6º Secundaria',
                'titulo_fecha1' => 'Categoría A',
                'fecha1' => '2025-10-26',
                'titulo_fecha2' => 'Categoría B',
                'fecha2' => '2025-10-26',
                'lugar' => 'Ing. Mecánica, Electromecánica, Mecatrónica',
                'modalidad' => 'Presencial',
                'inscripcion' => 'Hasta el 24/10/2025 17:30, en secretaria de la carrera – Ciudadela Universitaria F.N.I.',
            ]),
        ]);
    }
}
